# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chicago Design System
email: design-system@cityofchicago.org
description: The Chicago Design System (CDS) is a guide to producing delightful services and technology applications for employees and residents of the City of Chicago.
# >- this means to ignore newlines until "baseurl:" I didn't try this, though.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chicagodesignsystem.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChiDesignDir
github_username:  chicago
repository: "Chicago/design-system"
google_analytics: "UA-120815826-1"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
 # - jekyll-paginate
  
# paginate: 5
# paginate_path: "/pages/blog/page:num/"

collections_dir: pages
collections:
  guides:
    output: true
    permalink: /:collection/:path
  identity:
    output: true
    permalink: /:collection/:path
  getting-started:
    output: true
    permalink: /:collection/:path
  downloadable-assets:
    output: false
    permalink: /:collection/:path
# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
